### PR TITLE
Update MALI tpls on pmcpu & add pmgpu build

### PR DESCRIPTION
**Pull request by jewatkins**
This:
 - updates MALI tpl paths for pmcpu (old albany build was using the wrong SFAD size which may fail at times and increase memory usage)
 - adds MALI tpls for pmgpu
 - adds capability to use different albany input files depending on **machine**. This is needed to use different (possibly tuned) solvers for each machine. For example, we use a different solver on gpu machines.
 
 @mperego
 
 @stephenprice I was hoping to sneak this into your PR if possible but I could make a new PR after yours is pushed.

I've only tested 
```
SMS.ne30pg2_r05_EC30to60E2r2_gis20.IGELM_MLI.pm-cpu_gnu.elm-gis20kmSMS
SMS.ne30pg2_r05_EC30to60E2r2_gis20.IGELM_MLI.pm-gpu_gnu.elm-gis20kmSMS
```
but I could try other tests.

### CODE REVIEW

**Comment by jewatkins** [comment]
Also, I'm not too certain on how optimal those albany input files are, I just didn't want to change any settings (besides cpu->gpu solver) in this PR.

**Comment by stephenprice** [comment]
@jewatkins, @mperego - I'm going to revisit these suggested changes now that the rest of that PR is on master. 

For the machine file changes, master currently has these paths for the Trilinos, Albany, and Kokkos support for pm-cpu:

```
/global/common/software/e3sm/mali_tpls/albany-e3sm-serial-release-gcc-cmake-fix
/global/common/software/e3sm/mali_tpls/trilinos-e3sm-serial-release-gcc
/global/common/software/e3sm/mali_tpls/trilinos-e3sm-serial-release-gcc
```
 
... whereas Jerry would like to point these to "...-pm-cpu-gnu-release-e3sm-2023-02-22"

Is the latter still the preference? If so, I can start a new PR that includes those changes (since this one is into a no-longer-there branch). I could also add the suggested pm-gpu machine file changes.

The buildnml changes around albany's yaml file make sense to me too r.e. eventual cpu vs. gpu support. But I wanted to check on the default yaml file changes themselves since we just updated those in this last PR. I am happy to test them out but thought maybe Mauro could skim them over first to make sure he thinks they make sense? Current default yaml file is [here](https://github.com/stephenprice/E3SM/blob/master/components/mpas-albany-landice/bld/namelist_files/albany_input.yaml).

(Actually maybe I'm seeing now that the default 'albany_input.yaml' file was just renamed here to 'albany_input_cpu.yaml', so skip that last question?)

**Comment by jewatkins** [comment]
Hi Steve, we decided to wait for the kokkos 4.2 PR to go through to revisit this.
https://github.com/E3SM-Project/E3SM/pull/6101
It will change all the builds. I can then look at the new yaml settings and create a new gpu yaml file.

**Comment by mperego** [comment]
@stephenprice B.t.w. any plan to add a BG test? That will expose more potential build issues.

**Comment by stephenprice** [comment]
@perego -- yes, I'll add a BG test as part of the follow up to that last PR. 
@Jerry -- so I should put all of the changes proposed in this PR on hold for now? Thanks both.

**Comment by jewatkins** [comment]
> so I should put all of the changes proposed in this PR on hold for now?

Yes, I'll create a new PR that will include some of these changes, thanks.

**Comment by stephenprice** [comment]
Ok, thanks. So I'll scrub working on this for now.

**Comment by stephenprice** [comment]
I don't know what you want to do w/ this PR, but I'll leave that to you!

**Comment by mperego** [comment]
@stephenprice FYI, as soon as Luca's PR is merged you won't be able to add the BG test because E3SM is switching to Kokkos 4.2 while Albany/Trilinos libs are built with Kokkos 3.x. 
Jerry's PR will update Albany/Trilinos libs to be consistent with Kokkos 4.2.

**Pull request closed without merging**
